server:
  port: 8086
hm:
  db:
    database: hm-trade
    host: 192.168.58.129 # 修改为你自己的虚拟机IP地址
    pw: 123 # 修改为docker中的MySQL密码
  swagger:
    title: "交易接口文档"
    package: com.hmall.trade.controller
